title: Chenyu Wang
# logo: 照片.jpeg
description: Final-year Undergraduate Student @ Tsinghua \\ mail: wangchy.18@sem.tsinghua.edu.cn
show_downloads: false
# google_analytics:
theme: jekyll-theme-minimal
path: https://chenyuwang-monica.github.io/
