# encoding: UTF-8
title: Chenyu Wang
affiliation: Massachusetts Institute of Technology
email: wangchy@mit.edu # or cy-wang18@mails.tsinghua.edu.cn
google_scholar: https://scholar.google.com/citations?user=Kq0dhLAAAAAJ&hl
# github_link: https://github.com/yaoyao-liu/minimal-light
linkedin: https://www.linkedin.com/in/chenyu-wang-3a6a9a193/
avatar: photo1.jpeg
google_analytics: UA-211240572-1
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
# description: The Minimal Light is a simple and elegant jekyll theme for academic personal homepage.
# canonical: https://minimal-light.yyliu.net/
remote_theme: yaoyao-liu/minimal-light
